In [1]:
import pandas as pd
import numpy as np

Question 1

What's the version of NumPy that you installed?

You can get the version information using the __version__ field:

np.__version__

In [2]:
np.__version__

'1.21.6'

In [4]:
!wget https://raw.githubusercontent.com/alexeygrigorev/mlbookcamp-code/master/chapter-02-car-price/data.csv

--2022-09-12 18:26:31--  https://raw.githubusercontent.com/alexeygrigorev/mlbookcamp-code/master/chapter-02-car-price/data.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1475504 (1.4M) [text/plain]
Saving to: ‘data.csv’

data.csv            100%[===================>]   1.41M  --.-KB/s    in 0.09s   

2022-09-12 18:26:32 (16.3 MB/s) - ‘data.csv’ saved [1475504/1475504]



In [82]:
df = pd.read_csv('data.csv')

Question 2

How many records are in the dataset?

Here you need to specify the number of rows.

In [10]:
df.shape

(11914, 16)

In [11]:
df.head()

Make       Model  Year             Engine Fuel Type  Engine HP  \
0  BMW  1 Series M  2011  premium unleaded (required)      335.0   
1  BMW    1 Series  2011  premium unleaded (required)      300.0   
2  BMW    1 Series  2011  premium unleaded (required)      300.0   
3  BMW    1 Series  2011  premium unleaded (required)      230.0   
4  BMW    1 Series  2011  premium unleaded (required)      230.0   

   Engine Cylinders Transmission Type     Driven_Wheels  Number of Doors  \
0               6.0            MANUAL  rear wheel drive              2.0   
1               6.0            MANUAL  rear wheel drive              2.0   
2               6.0            MANUAL  rear wheel drive              2.0   
3               6.0            MANUAL  rear wheel drive              2.0   
4               6.0            MANUAL  rear wheel drive              2.0   

                         Market Category Vehicle Size Vehicle Style  \
0  Factory Tuner,Luxury,High-Performance      Compact         Coupe   
1                     Luxury,Performance      Compact   Convertible   
2                Luxury,High-Performance      Compact         Coupe   
3                     Luxury,Performance      Compact         Coupe   
4                                 Luxury      Compact   Convertible   

   highway MPG  city mpg  Popularity   MSRP  
0           26        19        3916  46135  
1           28        19        3916  40650  
2           28        20        3916  36350  
3           28        18        3916  29450  
4           28        18        3916  34500

Question 3

Who are the most frequent car manufacturers (top-3) according to the dataset?

In [15]:
df.Make.value_counts()

Chevrolet        1123
Ford              881
Volkswagen        809
Toyota            746
Dodge             626
Nissan            558
GMC               515
Honda             449
Mazda             423
Cadillac          397
Mercedes-Benz     353
Suzuki            351
BMW               334
Infiniti          330
Audi              328
Hyundai           303
Volvo             281
Subaru            256
Acura             252
Kia               231
Mitsubishi        213
Lexus             202
Buick             196
Chrysler          187
Pontiac           186
Lincoln           164
Oldsmobile        150
Land Rover        143
Porsche           136
Saab              111
Aston Martin       93
Plymouth           82
Bentley            74
Ferrari            69
FIAT               62
Scion              60
Maserati           58
Lamborghini        52
Rolls-Royce        31
Lotus              29
Tesla              18
HUMMER             17
Maybach            16
Alfa Romeo          5
McLaren             5
Spyker    

Question 4

What's the number of unique Audi car models in the dataset?

In [20]:
df[df['Make' ] == 'Audi'].Model.nunique()

34

Question 5

How many columns in the dataset have missing values?

In [22]:
df.isnull().sum()

Make                    0
Model                   0
Year                    0
Engine Fuel Type        3
Engine HP              69
Engine Cylinders       30
Transmission Type       0
Driven_Wheels           0
Number of Doors         6
Market Category      3742
Vehicle Size            0
Vehicle Style           0
highway MPG             0
city mpg                0
Popularity              0
MSRP                    0
dtype: int64

**Question 6**

Find the median value of "Engine Cylinders" column in the dataset.

Next, calculate the most frequent value of the same "Engine Cylinders".

Use the fillna method to fill the missing values in "Engine Cylinders" with the most frequent value from the previous step.

Now, calculate the median value of "Engine Cylinders" once again.

Has it changed?



In [25]:
df['Engine Cylinders'].median()

6.0

In [33]:
df['Engine Cylinders'].value_counts()

4.0     4752
6.0     4489
8.0     2031
12.0     230
5.0      225
10.0      68
0.0       56
3.0       30
16.0       3
Name: Engine Cylinders, dtype: int64

In [35]:
df['Engine Cylinders'].isnull().sum()

30

In [43]:
df['Engine Cylinders'] = df['Engine Cylinders'].fillna(4.0)

In [44]:
df['Engine Cylinders'].value_counts()

4.0     4782
6.0     4489
8.0     2031
12.0     230
5.0      225
10.0      68
0.0       56
3.0       30
16.0       3
Name: Engine Cylinders, dtype: int64

In [45]:
df['Engine Cylinders'].median()

6.0

**Question 7**

Select all the "Lotus" cars from the dataset.

Select only columns "Engine HP", "Engine Cylinders".

Now drop all duplicated rows using drop_duplicates method (you should get a dataframe with 9 rows).

Get the underlying NumPy array. Let's call it X.

Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.

Compute the inverse of XTX.

Create an array y with values [1100, 800, 750, 850, 1300, 1000, 1000, 1300, 800].

Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.

What's the value of the first element of w?

In [83]:
lotus = df[df['Make'] == 'Lotus']
lotus = lotus[['Engine HP', 'Engine Cylinders']].drop_duplicates()

In [84]:
X = lotus.values
X

array([[189.,   4.],
       [218.,   4.],
       [217.,   4.],
       [350.,   8.],
       [400.,   6.],
       [276.,   6.],
       [345.,   6.],
       [257.,   4.],
       [240.,   4.]])

In [85]:
#transpose of X
X.T

array([[189., 218., 217., 350., 400., 276., 345., 257., 240.],
       [  4.,   4.,   4.,   8.,   6.,   6.,   6.,   4.,   4.]])

In [88]:
XTX = X.T.dot(X)
XTX

array([[7.31684e+05, 1.34100e+04],
       [1.34100e+04, 2.52000e+02]])

In [89]:
XTX_inv = np.linalg.inv(XTX)

In [66]:
y = np.array([1100, 800, 750, 850, 1300, 1000, 1000, 1300, 800])

In [90]:
w = XTX_inv.dot(X.T).dot(y)

In [91]:
w

array([  4.59494481, -63.56432501])